config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  root "home#index"
  
  get 'home/index'
  resources :sales
  resources :products
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sales, :dependent => :destroy
  
  validates_presence_of :name, :mail
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :sales, :dependent => :destroy
  
  validates_presence_of :name, :price
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :client
  belongs_to :product
  
  validates :client, presence: true
  validates :product, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :mail, :birth_date)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :price)
    end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: %i[ show edit update destroy ]
  before_action :set_product_options, only: [ :edit, :update, :create, :new]
  before_action :set_client_options, only: [ :edit, :update, :create, :new]

  # GET /sales or /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1 or /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales or /sales.json
  def create
    @sale = Sale.new(sale_params)
    
    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: "Sale was successfully created." }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1 or /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: "Sale was successfully updated." }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1 or /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: "Sale was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client_options
      @client_name = Client.order(:name)
    end
    
    def set_product_options
      @product_name= Product.order(:name)
    end
    
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sale_params
      params.require(:sale).permit( :client_id, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation" class="text-danger">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Enter with your name" %>
  </div>

  <div class="form-group">
    <%= form.label :mail, class:"form-label" %>
    <%= form.text_field :mail, class:"form-control", placeholder:"Enter with your mail" %>
  </div>

  <div class="form-group">
    <%= form.label :birth_date, class:"form-label" %>
    <%= form.date_field( :birth_date, class:"form-select") %>
  </div>
  <hr>
  <div class="actions">
    <%= form.submit nil, class:"btn btn-info"  %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h3>Editing Client</h3>

<%= render 'form', client: @client %>

</br>
<%= link_to 'Show', @client, class:"btn btn-info" %> 

app/views/clients/index.html.erb
<p id="notice" class="text-success"><%= notice %></p>

<h3>Clients</h3>

<table class= "table table-dark table-hover text-info">
  <thead>
    <tr>
      <th width="10%" height="10"; >Name</th>
      <th width="10%" height="10"; >Mail</th>
      <th width="10%" height="10"; >Birth date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td width="10%" height="10"; ><%= client.name %></td>
        <td width="10%" height="10"; ><%= client.mail %></td>
        <td width="10%" height="10"; ><%= client.birth_date %></td>
        <td width="2%" height="10"; ><%= link_to 'Show', client, class:"btn btn-info" %></td>
        <td width="2%" height="10"; ><%= link_to 'Edit', edit_client_path(client), class:"btn btn-info" %></td>
        <td width="2%" height="10"; ><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path, class:"btn btn-info" %>

app/views/clients/new.html.erb
<h3>New Client</h3>

<%= render 'form', client: @client %>

app/views/clients/show.html.erb
<p id="notice" class="text-success"><%= notice %></p>

<p class="text-info">
  <strong>Name:</strong>
  <%= @client.name%>
</p>

<p class="text-info">
  <strong>Mail:</strong>
  <%= @client.mail %>
</p>

<p class="text-info">
  <strong>Birth date:</strong>
  <%= @client.birth_date %>
</p>

<%= link_to 'Edit', edit_client_path(@client), class:"btn btn-info" %> 

app/views/home/index.html.erb
<h3 class="display-5">Wellcome</h3>

<p class="lead">
  This is the evolving product proposed by the challenge to Augusto César.
</p>
<p class="lead">
  Here we have a client area that can be accessed through the link at the 
  top on the right, next to product and sales.
</p>
<p class="lead">
  A new customer can only be entered if there is a name and an email entered, 
  as well as product name and price, sales need to be placed a customer and at 
  least one product.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# stylesheet_link_tag    params[:controller], media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# javascript_include_tag params[:controller], 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-dark">
    <header>
      <div id="header-wrap" class="container-fluid">
        <h1><%= link_to "Let's Start This Challange", root_path, class:"nav-link link-info display-4" %> </h1>
        <nav>
          <ul class="nav justify-content-end">
            <li class:"nav-item">
              <%= link_to "Clients", clients_path, class:"nav-link link-info"%>
            </li>
              |
            <li class:"nav-item">
              <%= link_to "Products", products_path, class:"nav-link link-info" %>
            </li>
              |
            <li class:"nav-item">
              <%= link_to "Sales", sales_path, class:"nav-link link-info" %>
            </li>
          </ul>
        </nav>
        <hr>
        <hr class="bg-light">
      </div>
    </header>
    <div id="content py-4" class="h-100 p-5 hounded-3 container-fluid border col-md-11 text-info">

        <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation" class="text-danger">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class:"form-label"%>
    <%= form.text_field :name, class:"form-control", placeholder:"Enter with name of the product" %>
  </div>

  <div class="form-group">
    <%= form.label :description, class:"form-label" %>
    <%= form.text_field :description, class:"form-control", placeholder:"Enter with the description" %>
  </div>

  <div class="form-group">
    <%= form.label :price, class:"form-label" %>
    <%= form.text_field :price, class:"form-control", placeholder:"Enter with the price" %>
  </div>
  <hr>
  <div class="actions">
    <%= form.submit nil, class:"btn btn-info" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h3>Editing Product</h3>

<%= render 'form', product: @product %>

</br>
<%= link_to 'Show', @product, class:"btn btn-info" %> 

app/views/products/index.html.erb
<p id="notice" class="text-success"><%= notice %></p>

<h3>Products</h3>

<table class= "table table-dark table-hover text-info">
  <thead>
    <tr>
      <th width="30%" height="10"; >Name</th>
      <th width="30%" height="10"; >Description</th>
      <th width="30%" height="10"; >Price</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td width="30%" height="10"; ><%= link_to product.name, product, class:"link-info" %></td>
        <td width="30%" height="10"; ><%= product.description %></td>
        <td width="30%" height="10"; ><%= product.price %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path, class:"btn btn-info" %>

app/views/products/new.html.erb
<h3>New Product</h3>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<p id="notice" class="text-success"><%= notice %></p>

<p class="text-info">
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p class="text-info">
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p class="text-info">
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p class="text-info">
  <%= link_to 'Edit', edit_product_path(@product), class:"btn btn-info" %> |
  <%= link_to 'Destroy', product_path(@product), method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-info" %>
<p/>

app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation" class="text-danger">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :client_id, class:"form-label" %>
    <%= form.collection_select( :client_id, @client_name, :id, :name, { include_blank: "Select Client"}, class:"form-select") %>
  </div>

  <div class="form-group">
    <%= form.label :product_id, class:"form-label" %>
    <%= form.collection_select( :product_id, @product_name, :id, :name, { include_blank: "Select Product"}, class:"form-select" )%>
    
  </div>
  <hr>
  <div class="actions">
    <%= form.submit nil, class:"btn btn-info"  %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h3>Editing Sale</h3>

<%= render 'form', sale: @sale %>

</br>
<%= link_to 'Show', @sale, class:"btn btn-info" %> 

app/views/sales/index.html.erb
<p id="notice" class="text-success"><%= notice %></p>

<h3>Sales</h3>

<table class= "table table-dark table-hover text-info">
  <thead>
    <tr>
      <th>Client</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td width="10%" height="10"; ><%= sale.client.name %></td>
        <td width="10%" height="10"; ><%= sale.product.name %></td>
        <td width="2%" height="10"; ><%= link_to 'Show', sale, class:"btn btn-info" %></td>
        <td width="2%" height="10"; ><%= link_to 'Edit', edit_sale_path(sale), class:"btn btn-info" %></td>
        <td width="2%" height="10"; ><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path, class:"btn btn-info"%>

app/views/sales/new.html.erb
<h3>New Sale</h3>


<%= render 'form', sale: @sale %>

app/views/sales/show.html.erb
<p id="notice" class="text-success"><%= notice %></p>

<p class="text-info">
  <strong>Client:</strong>
  <%= @sale.client.name %>
</p>

<p class="text-info">
  <strong>Product:</strong>
  <%= @sale.product.name %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale), class:"btn btn-info"%> 

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>